ENV= "development"

[API]
port = ":8000"
server_cert = "/opt/data/chessapi/x509/server_cert.pem"
server_key = "/opt/data/chessapi/x509/server_key.pem"

[Database]
host = "127.0.0.1"
port = "5432"
db_name = "chess_api"

[HTTP_server]
Scheme = "http"
Host = "localhost"
Port = ":8080"
