---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: secret-sa-sample
#   annotations:
#     kubernetes.io/service-account.name: "sa-name"
# type: kubernetes.io/service-account-token
# data:
#   # You can include additional key value pairs as you do with Opaque Secrets
#   extra: YmFyCg==
#
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresqlcreds
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  # TODO:
  # 1. https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/
  # 2. https://kubernetes.io/docs/reference/access-authn-authz/authorization/
  username: cG9zdGdyZXM=
  password: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: grpccerts
type: kubernetes.io/tls
# You can include additional key value pairs as you do with Opaque Secrets
# TODO:
# 1. https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/
# 2. https://kubernetes.io/docs/reference/access-authn-authz/authorization/
data:
  # cat certs/x509/fabrikam.crt | base64
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBakNDQWFnQ0NRQ0ZkMkNjYktoNW5qQUtCZ2dxaGtqT1BRUURBakNCZ3pFTE1Ba0dBMVVFQmhNQ1ZWTXgKRGpBTUJnTlZCQWdNQlZSbGVHRnpNUTh3RFFZRFZRUUhEQVpCZFhOMGFXNHhDekFKQmdOVkJBb01BazFUTVFzdwpDUVlEVlFRTERBSkVRekVZTUJZR0ExVUVBd3dQZDNkM0xtTnZiblJ2YzI4dVkyOXRNUjh3SFFZSktvWklodmNOCkFRa0JGaEIxYzJWeVFHTnZiblJ2YzI4dVkyOXRNQjRYRFRJeE1EVXhNakUyTXpnMU4xb1hEVEl5TURVeE1qRTIKTXpnMU4xb3dnWTB4Q3pBSkJnTlZCQVlUQWtsT01SSXdFQVlEVlFRSURBbFVaV3hoYm1kaGJtRXhFakFRQmdOVgpCQWNNQ1VoNVpHVnlZV0poWkRFTE1Ba0dBMVVFQ2d3Q1RWTXhEREFLQmdOVkJBc01BMGxFUXpFWk1CY0dBMVVFCkF3d1FkM2QzTG1aaFluSnBhMkZ0TG1OdmJURWdNQjRHQ1NxR1NJYjNEUUVKQVJZUmRYTmxja0JtWVdKeWFXdGgKYlM1amIyMHdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUlpRNERFQzNPVFNpSXY0WnNiWEVHcwpLclh4T1RCY25tSDl4S2U3L0h5T3JUVjc0Z1N2akhLYWlNYVRwc1RqU3BDbkhqdDRBZDdUS0VXcXc3RFhrYi9GCk1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lEOXpEM0NmMlJCOUtSRkxkSWg3RzdsNEtWRzZicEpnaWtycVNqR0MKdXpOYkFpRUFxT2RBMUdBZzFCb0ZabDA5Sks2WFlpT0pvZU5hU0JGRHdDUUVJdTRvY2xzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  # cat certs/x509/fabrikam.key | base64
  tls.key: |
    LS0tLS1CRUdJTiBFQyBQQVJBTUVURVJTLS0tLS0KQmdncWhrak9QUU1CQnc9PQotLS0tLUVORCBFQyBQQVJBTUVURVJTLS0tLS0KLS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUJvM2prS2FvVHdlVVNuY05kVkpNMzlLS291bmVZSVM1bG1URDZEcGR5MmxvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFV1VPQXhBdHprMG9pTCtHYkcxeEJyQ3ExOFRrd1hKNWgvY1NudS94OGpxMDFlK0lFcjR4eQptb2pHazZiRTQwcVFweDQ3ZUFIZTB5aEZxc093MTVHL3hRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
