---
apiVersion: v1
kind: Service
metadata:
  name: chess
  labels:
    app: chess
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      name: grpc
      targetPort: 8000
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: chess
