---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: chess
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: postgresql
  selector:
    app: chess
---
# TODO: add PVC and PV
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  labels:
    app: chess
spec:
  selector:
    matchLabels:
      app: chess
  serviceName: postgresql
  replicas: 1  # default is 1
  template:
    metadata:
      labels:
        app: chess
    spec:
      containers:
        - name: postgresql
          image: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: chess-conf
                  key: database_name
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresqlcreds
                  key: password
          ports:
            - containerPort: 5432
              name: postgresql
